### Recuperar todas las películas
GET http://localhost:3000/movies

### Recuperar una película por id
GET http://localhost:3000/movies/64ed88d989eb31b76332f6bb

### Recuperar películas por géneros
GET http://localhost:3000/movies?genre=DRAMA

### Crear una pelicula con POST (crear todo el recurso desde cero)
POST http://localhost:3000/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "The Goodfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Provocando errores en la creacion del recurso movie
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": 1,
  "year": "cualquier baina"
}

### Eliminar una pelicula con DELETE
DELETE http://localhost:3000/movies/64ed8c318dfefc7c4ff76b70

### Modificar o actualizar solo alguna parte de una movie
PATCH http://localhost:3000/movies/64ed88d989eb31b76332f6bb
Content-Type: application/json

{
  "id": "kdfjiaefhk",
  "year": 1993,
  "title": "Hola"
}
